### ISSUE TITLE
explorer the usage of git2go 

### ISSUE THREAD

**Issue by groenborg** [Praqma/OurDefaultGithubIssuesWorkflow#32]
See if git2go can caretake the jobs we wan't it to complete. Function a viable replacement for the os/exec calls which git-lfs heavily depends on

**Comment by JKrag** [comment]
It might be worth it to take a quick look at https://github.com/src-d/go-git as well. This seems to be a viable alternative that implements the needed parts in pure Go instead of wrapping the libgit2 C libraries. 

I am pretty convinced that we should use one of the two rather than Exec'ing to an installed Git, but lets see what the investigation brings to the table.

**Comment by groenborg** [comment]
It actually look really interesting, the documentation seems better as well! I think we should have a discussion about this
